### ISSUE TITLE
Option to set sub-second precision times

### ISSUE THREAD

**Issue by sourcefrog** [simnalamburt/utime#16]
Both Windows and Unix have ways to set the mtime with sub-second precision. It'd be nice to plumb this through Rust utime. 

I can send you a PR if you like - should be pretty straightforward as you are already using OS APIs that support this.

**Comment by simnalamburt** [comment]
If it can be done in backward-compatible manner, there's no reason to reject your PR! Please send it if you feel free :)

**Comment by simnalamburt** [comment]
Fixed as of Rust 1.75.0

###### Reference
- https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#:~:text=FileTimes,File%3A%3Aset_times
- https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.set_times
