### ISSUE TITLE
Reconsider API

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/utime#2]
- [x] Getter function - #7 
- [ ] `u64` is not appropriate type for representing time
- [ ] Separate `atime` setter and `mtime` setter only for Windows, see https://github.com/simnalamburt/utime/pull/13#issuecomment-428220225

**Comment by mmstick** [comment]
This would work better as a trait, too.

```rust
pub trait Utime {
}

impl Utime for File {}
```

**Comment by simnalamburt** [comment]
Sadly, "File" struct cannot know its corresponding "Path", so we cannot use
this approach

2018년 10월 5일 (금) 오전 6:41, Michael Murphy <notifications@github.com>님이 작성:

**Comment by sourcefrog** [comment]
The current API uses `u64` for the time, but Unix times are signed integers <https://stackoverflow.com/a/471287/243712> and it'd be nice to have a cleaner way to pass them.

It would also be nice to be able to access sub-second precision APIs like `utimes` on Linux.

**Comment by simnalamburt** [comment]
Fixed as of Rust 1.75.0

###### Reference
- https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#:~:text=FileTimes,File%3A%3Aset_times
- https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.set_times
